#! /bin/bash

# https://mybinder.readthedocs.io/en/latest/using.html#postbuild

jupyter nbextension install --user
jupyter nbextension enable --py widgetsnbextension

cat > ~/.jupyter/jupyter_notebook_config.py <<EOF
c.NotebookApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors https://relate.cs.illinois.edu 'self' "
    }
}
EOF
